export const bookingsData = [
  {
    id: 1,
    customerName: "Nguyễn Thị Lan",
    email: "lan.nguyen@email.com",
    phone: "0123456789",
    service: "Massage thư giãn toàn thân",
    date: "2024-12-16",
    time: "09:00",
    duration: 90,
    price: 800000,
    status: "confirmed",
    therapist: "Nguyễn Thị Lan",
    notes: "Khách hàng VIP, cần phòng riêng",
  },
  {
    id: 2,
    customerName: "Trần Văn Nam",
    email: "nam.tran@email.com",
    phone: "0987654321",
    service: "Chăm sóc da mặt cao cấp",
    date: "2024-12-16",
    time: "10:30",
    duration: 75,
    price: 650000,
    status: "in-progress",
    therapist: "Lê Thị Hoa",
    notes: "Da nhạy cảm, cần sản phẩm organic",
  },
  {
    id: 3,
    customerName: "Lê Thị Hoa",
    email: "hoa.le@email.com",
    phone: "0369852147",
    service: "Gói spa toàn thân VIP",
    date: "2024-12-16",
    time: "14:00",
    duration: 180,
    price: 1200000,
    status: "pending",
    therapist: "",
    notes: "Lần đầu sử dụng dịch vụ",
  },
  {
    id: 4,
    customerName: "Phạm Minh Tuấn",
    email: "tuan.pham@email.com",
    phone: "0741852963",
    service: "Massage đá nóng",
    date: "2024-12-16",
    time: "15:30",
    duration: 75,
    price: 900000,
    status: "confirmed",
    therapist: "Trần Văn Nam",
    notes: "Đau lưng, cần massage nhẹ nhàng",
  },
  {
    id: 5,
    customerName: "Võ Thị Mai",
    email: "mai.vo@email.com",
    phone: "0258147369",
    service: "Tắm trắng toàn thân",
    date: "2024-12-17",
    time: "09:00",
    duration: 120,
    price: 750000,
    status: "pending",
    therapist: "",
    notes: "Cần tư vấn về sản phẩm",
  },
  {
    id: 6,
    customerName: "Đặng Văn Hùng",
    email: "hung.dang@email.com",
    phone: "0147258369",
    service: "Massage thư giãn toàn thân",
    date: "2024-12-17",
    time: "11:00",
    duration: 90,
    price: 800000,
    status: "confirmed",
    therapist: "Nguyễn Thị Lan",
    notes: "Khách hàng thường xuyên",
  },
  {
    id: 7,
    customerName: "Bùi Thị Nga",
    email: "nga.bui@email.com",
    phone: "0963852741",
    service: "Chăm sóc da mặt cao cấp",
    date: "2024-12-17",
    time: "14:30",
    duration: 75,
    price: 650000,
    status: "completed",
    therapist: "Lê Thị Hoa",
    notes: "Hài lòng với dịch vụ",
  },
  {
    id: 8,
    customerName: "Hoàng Văn Đức",
    email: "duc.hoang@email.com",
    phone: "0852741963",
    service: "Massage đá nóng",
    date: "2024-12-18",
    time: "10:00",
    duration: 75,
    price: 900000,
    status: "pending",
    therapist: "",
    notes: "Cần xác nhận lại thời gian",
  },
  {
    id: 9,
    customerName: "Ngô Thị Linh",
    email: "linh.ngo@email.com",
    phone: "0741963852",
    service: "Gói spa toàn thân VIP",
    date: "2024-12-18",
    time: "15:00",
    duration: 180,
    price: 1200000,
    status: "confirmed",
    therapist: "Phạm Minh Tuấn",
    notes: "Sinh nhật, cần trang trí đặc biệt",
  },
  {
    id: 10,
    customerName: "Lý Văn Thành",
    email: "thanh.ly@email.com",
    phone: "0369741852",
    service: "Tắm trắng toàn thân",
    date: "2024-12-19",
    time: "09:30",
    duration: 120,
    price: 750000,
    status: "cancelled",
    therapist: "",
    notes: "Khách hàng hủy do bận việc",
  },
]
