export const notificationsData = [
  {
    id: 1,
    title: "Xác nhận lịch hẹn",
    content: "Lịch hẹn massage thư giãn của bạn đã được xác nhận cho ngày 16/12/2024 lúc 09:00",
    type: "email",
    recipient: "lan.nguyen@email.com",
    recipientType: "individual",
    status: "sent",
    sentAt: "2024-12-15T14:30:00Z",
    scheduledAt: null,
    template: "booking-confirmation",
    priority: "normal",
  },
  {
    id: 2,
    title: "Nhắc nhở lịch hẹn",
    content: "Nhắc nhở: Bạn có lịch hẹn chăm sóc da mặt vào 10:30 ngày mai tại Elysian Spa",
    type: "sms",
    recipient: "0987654321",
    recipientType: "individual",
    status: "sent",
    sentAt: "2024-12-15T18:00:00Z",
    scheduledAt: null,
    template: "booking-reminder",
    priority: "high",
  },
  {
    id: 3,
    title: "Khuyến mãi đặc biệt",
    content: "🎉 Giảm 30% tất cả dịch vụ massage trong tháng 12! Đặt lịch ngay để không bỏ lỡ.",
    type: "email",
    recipient: "Tất cả khách hàng",
    recipientType: "all",
    status: "scheduled",
    sentAt: null,
    scheduledAt: "2024-12-17T09:00:00Z",
    template: "promotion",
    priority: "normal",
  },
  {
    id: 4,
    title: "Chúc mừng sinh nhật",
    content: "Chúc mừng sinh nhật! Elysian Spa tặng bạn voucher giảm 50% và quà tặng đặc biệt.",
    type: "email",
    recipient: "hoa.le@email.com",
    recipientType: "individual",
    status: "pending",
    sentAt: null,
    scheduledAt: "2024-12-18T08:00:00Z",
    template: "birthday",
    priority: "normal",
  },
  {
    id: 5,
    title: "Yêu cầu đánh giá dịch vụ",
    content: "Cảm ơn bạn đã sử dụng dịch vụ. Vui lòng đánh giá trải nghiệm để chúng tôi cải thiện.",
    type: "email",
    recipient: "tuan.pham@email.com",
    recipientType: "individual",
    status: "sent",
    sentAt: "2024-12-15T16:45:00Z",
    scheduledAt: null,
    template: "feedback",
    priority: "low",
  },
  {
    id: 6,
    title: "Thông báo thay đổi lịch",
    content: "Lịch hẹn của bạn đã được chuyển từ 14:00 sang 15:30 cùng ngày. Xin lỗi vì sự bất tiện.",
    type: "sms",
    recipient: "0369852147",
    recipientType: "individual",
    status: "failed",
    sentAt: null,
    scheduledAt: null,
    template: "",
    priority: "urgent",
  },
  {
    id: 7,
    title: "Chương trình khách hàng thân thiết",
    content: "Bạn đã tích lũy đủ điểm để nhận ưu đãi VIP! Ghé spa để nhận quà tặng đặc biệt.",
    type: "push",
    recipient: "Khách hàng VIP",
    recipientType: "vip",
    status: "sent",
    sentAt: "2024-12-15T12:00:00Z",
    scheduledAt: null,
    template: "",
    priority: "normal",
  },
  {
    id: 8,
    title: "Mời tham gia sự kiện",
    content: "Elysian Spa tổ chức workshop chăm sóc da tự nhiên. Đăng ký miễn phí cho 20 khách hàng đầu tiên!",
    type: "email",
    recipient: "Khách hàng chăm sóc da",
    recipientType: "group",
    status: "scheduled",
    sentAt: null,
    scheduledAt: "2024-12-20T10:00:00Z",
    template: "",
    priority: "normal",
  },
]
