export const servicesData = [
  {
    id: 1,
    name: "Massage thư giãn toàn thân",
    description: "Massage thư giãn với tinh dầu thiên nhiên, giúp giảm căng thẳng và mệt mỏi",
    category: "massage",
    price: 800000,
    originalPrice: 1000000,
    duration: 90,
    benefits: ["Thư giãn cơ bắp", "Giảm stress", "Cải thiện tuần hoàn máu", "Tăng cường sức khỏe"],
    status: "active",
    rating: 4.8,
    reviewCount: 124,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 2,
    name: "Chăm sóc da mặt cao cấp",
    description: "Liệu trình chăm sóc da mặt chuyên sâu với công nghệ hiện đại",
    category: "skincare",
    price: 650000,
    originalPrice: null,
    duration: 75,
    benefits: ["Làm sạch sâu", "Cấp ẩm", "Chống lão hóa", "Làm sáng da"],
    status: "active",
    rating: 4.9,
    reviewCount: 89,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 3,
    name: "Gói spa toàn thân VIP",
    description: "Gói dịch vụ cao cấp bao gồm massage, chăm sóc da và thư giãn",
    category: "package",
    price: 1200000,
    originalPrice: 1500000,
    duration: 180,
    benefits: ["Massage toàn thân", "Chăm sóc da mặt", "Tắm thảo dược", "Thư giãn hoàn toàn"],
    status: "active",
    rating: 4.7,
    reviewCount: 67,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 4,
    name: "Massage đá nóng",
    description: "Massage với đá nóng tự nhiên, giúp thư giãn cơ bắp sâu",
    category: "massage",
    price: 900000,
    originalPrice: null,
    duration: 75,
    benefits: ["Thư giãn cơ bắp sâu", "Cải thiện tuần hoàn", "Giảm đau nhức", "Tăng cường năng lượng"],
    status: "active",
    rating: 4.6,
    reviewCount: 45,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 5,
    name: "Tắm trắng toàn thân",
    description: "Liệu trình tắm trắng an toàn với thành phần tự nhiên",
    category: "body",
    price: 750000,
    originalPrice: 850000,
    duration: 120,
    benefits: ["Làm trắng da", "Loại bỏ tế bào chết", "Cấp ẩm", "Da mềm mại"],
    status: "active",
    rating: 4.5,
    reviewCount: 78,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 6,
    name: "Chăm sóc mắt chuyên sâu",
    description: "Liệu trình chăm sóc vùng mắt, giảm quầng thâm và nếp nhăn",
    category: "facial",
    price: 450000,
    originalPrice: null,
    duration: 45,
    benefits: ["Giảm quầng thâm", "Làm mờ nếp nhăn", "Cấp ẩm", "Làm sáng vùng mắt"],
    status: "inactive",
    rating: 4.4,
    reviewCount: 32,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 7,
    name: "Massage foot reflexology",
    description: "Massage bấm huyệt bàn chân theo phương pháp cổ truyền",
    category: "massage",
    price: 350000,
    originalPrice: null,
    duration: 60,
    benefits: ["Thư giãn", "Cải thiện tuần hoàn", "Giảm mệt mỏi", "Tăng cường sức khỏe"],
    status: "active",
    rating: 4.3,
    reviewCount: 156,
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 8,
    name: "Liệu trình detox cơ thể",
    description: "Liệu trình thải độc toàn thân với thảo dược tự nhiên",
    category: "body",
    price: 950000,
    originalPrice: 1100000,
    duration: 150,
    benefits: ["Thải độc", "Thanh lọc cơ thể", "Tăng cường miễn dịch", "Cải thiện sức khỏe"],
    status: "active",
    rating: 4.7,
    reviewCount: 23,
    image: "/placeholder.svg?height=200&width=300",
  },
]
